### ISSUE TITLE
Fresh Install Document

### ISSUE THREAD

**Issue by dlaflotte** [chopshop-166/tasks#7]
Need a document that outlines EXACTLY
1. Download/Install of VSCode
2. Download/Install of JDK
3. Download/Install Gradle Rio?
4. Download/Install Driver Station
5. Git Kraken

**Comment by msoucy** [comment]
GradleRIO is distributed as a folder structure. When we create the 2019 repo, it'll be initialized with GradleRIO. So that step is more like "download the code from github"
